stages:
  - linting
  - test

flake8:
  only:
    - pushes
    - merge_requests
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/test.txt
    - flake8 --verbose .

black:
  only:
    - pushes
    - merge_requests
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --verbose --line-length 79 .

django-test:
  only:
    - pushes
    - merge_requests
  stage: test
  image: python:3.12-slim
  before_script:
    - pip install -r requirements/test.txt
  script:
    - cd pastehub
    - python manage.py migrate
    - python manage.py test
