# Generated by Django 4.2.17 on 2024-12-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paste", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasteVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(verbose_name="номер версии")),
                (
                    "title",
                    models.CharField(
                        help_text="Максимальная длинна 150 символов",
                        max_length=150,
                        verbose_name="заголовок",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="обновлён"
                    ),
                ),
                (
                    "paste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paste.paste",
                        verbose_name="паста",
                    ),
                ),
            ],
            options={
                "verbose_name": "версия пасты",
                "verbose_name_plural": "версии паст",
            },
        ),
    ]
