# Generated by Django 4.2.17 on 2024-12-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paste", "0002_pasteversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pasteversion",
            name="paste",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="paste.paste",
                verbose_name="паста",
            ),
        ),
    ]
