# Generated by Django 4.2.17 on 2024-12-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paste", "0003_alter_pasteversion_paste"),
    ]

    operations = [
        migrations.AddField(
            model_name="pasteversion",
            name="short_link",
            field=models.CharField(
                default="aboba",
                max_length=10,
                unique=True,
                verbose_name="короткая ссылка",
            ),
            preserve_default=False,
        ),
    ]
