# Generated by Django 4.2.17 on 2024-12-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paste", "0004_pasteversion_short_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pasteversion",
            name="short_link",
            field=models.CharField(
                max_length=10, verbose_name="короткая ссылка"
            ),
        ),
    ]
